service: fizzy
image: ghcr.io/doan/fizzy

servers:
  web:
    - 178.128.28.249

ssh:
  user: deploy

proxy:
  ssl: true
  host: fizzy.teamblueotter.com

registry:
  server: ghcr.io
  username: doan
  password: <%= ENV.fetch("KAMAL_REGISTRY_PASSWORD") %>

env:
  clear:
    RAILS_ENV: production
    BASE_URL: https://fizzy.teamblueotter.com
    FORCE_SSL: "true"
    ASSUME_SSL: "true"

  secret:
    - SECRET_KEY_BASE
    - KAMAL_REGISTRY_PASSWORD

volumes:
  - "fizzy_storage:/rails/storage"

builder:
  arch: amd64
